### ISSUE TITLE
Error in Loading Addon 

### ISSUE THREAD

**Issue by Vexx662** [anhility/BestInSlotRedux#10]
Hi I got today the error with the addon that I cant load it with the erro taken from a bug addon:
```
6x ...ux_LegionDungeons\BestInSlotRedux_LegionDungeons-v7.3.06.lua:1580: attempt to call method 'RegisterExpansion' (a nil value)
...ux_LegionDungeons\BestInSlotRedux_LegionDungeons-v7.3.06.lua:1580: in function <...ux_LegionDungeons\BestInSlotRedux_LegionDungeons.lua:1579>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...s\BestInSlotRedux\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:558: in function `EnableAddon'
...s\BestInSlotRedux\Libs\AceAddon-3.0\AceAddon-3.0-12.lua:651: in function <...s\BestInSlotRedux\Libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:421: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:516: in function `TimeManager_LoadUI'
FrameXML\UIParent.lua:1098: in function <FrameXML\UIParent.lua:995>

Locals:
nil
```

**Comment by anhility** [comment]
Did you get this error when you first loaded the addon?

**Comment by Vexx662** [comment]
Yes everytime I try to open it I get this error. Before I installed this addon I got the Best in slot addon installed and for a short while the other best in slot addon. I deleted the other ones before installing the best in slot redux addon

**Comment by anhility** [comment]
The BestInSlotRedux_LegionDungeons.lua file have the version number appended for some reason. Please rename it and try logging in again if that helps.

**Comment by Vexx662** [comment]
Will try that when I am back on my pc thx for the fast help!

**Comment by anhility** [comment]
Your welcome. Tell if it doesn't work and I'll look into it tomorrow.

**Comment by anhility** [comment]
Do you still get the error or can I close the ticket?

**Comment by Vexx662** [comment]
The error is resolved with the new version from yesterday evening! Thx for the fast help!
