### ISSUE TITLE
Addon loading error

### ISSUE THREAD

**Issue by makwara** [anhility/BestInSlotRedux#13]
Downloaded this addon today and I (and at least one other person that I know of) are getting these errors when trying to use the addon:

- > 1x ...x\Libs\LibDBIcon-1.0\LibDBIcon-1.0\LibDBIcon-1.0.lua:12: LibDBIcon-1.0 requires LibDataBroker-1.1.
[C]: in function `error'
...x\Libs\LibDBIcon-1.0\LibDBIcon-1.0\LibDBIcon-1.0.lua:12: in main chunk
Locals:
(*temporary) = "LibDBIcon-1.0 requires LibDataBroker-1.1."

- > 1x BestInSlotRedux\MiniMapLDB.lua:3: Cannot find a library instance of "LibDataBroker-1.1".
[C]: in function `error'
Ace3\LibStub\LibStub.lua:23: in function `LibStub'
BestInSlotRedux\MiniMapLDB.lua:3: in main chunk
Locals:
(*temporary) = "Cannot find a library instance of "LibDataBroker-1.1"."

- > 1x BestInSlotRedux\Core.lua:507: attempt to call method 'MiniMapButtonVisible' (a nil value)
BestInSlotRedux\Core.lua:507: in function <BestInSlotRedux\Core.lua:498>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
Ace3\AceAddon-3.0\AceAddon-3.0-12.lua:558: in function `EnableAddon'
Ace3\AceAddon-3.0\AceAddon-3.0-12.lua:651: in function <Ace3\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
FrameXML\UIParent.lua:421: in function `UIParentLoadAddOn'
FrameXML\UIParent.lua:516: in function `TimeManager_LoadUI'
FrameXML\UIParent.lua:1098: in function <FrameXML\UIParent.lua:995>
Locals:
nil

**Comment by anhility** [comment]
It looks like a weird library linking problem. I'll look into it.

**Comment by makwara** [comment]
Alright, so we got it to work by copying **LibDataBroker-1.1** folder from another addon into **BestInSlotRedux\Libs** and now it works fine.

**Comment by anhility** [comment]
The linking error was found and fixed. Try updating.
