### ISSUE TITLE
Trash loots for Antorus

### ISSUE THREAD

**Issue by Nitrodroki** [anhility/BestInSlotRedux#19]
Hey, I'm Sannath (In the contributors for the original addon), still developping the addon for internal guild use.

Good luck with the addon ! :)

Here is the code for trashloots for antorus : 
  
```
  -----------------------------------
  ----- Trashloots
  -----------------------------------
  local bossName = "Trash Loots"
  local lootTable = {
  	152084, --Gloves of Abhorrent Strategies
	152085, --Cuffs of the Viridian Flameweavers
	153018, --Corrupted Mantle of the Felseekers
	151993, --Leggings of the Sable Stalkers
	152087, --Sinuous Kerapteron Bindings
	152413, --Felflame Inferno Shoulderpads
	152088, --Horror Fiend-Scale Breastplate
	152089, --Wristguards of Ominous Forging
	152682, --Greaves of the Felblade Defenders
	153019, --Hulking Demolisher Legplates
	152091, --Wristguards of the Dark Keepers
	152090, --Impenetrable Garothi Breastplate
  }
  
  self:RegisterBossLoot(ATBT, lootTable, bossName)
```

**Comment by anhility** [comment]
Cheers. Completely forgot about the trash loot. I'll add it in the next release.

**Comment by Nitrodroki** [comment]
Sure, Feng forgot it everytime as well :)
Fetching those precious item ID generally means you miss those pesky trash loots because they are neither in the codex nor in most database in the zone section :(

Happy to help

**Comment by anhility** [comment]
Commited and pushed. Will be in the next release on Monday.
