### ISSUE TITLE
Russian localization gives an error. 

### ISSUE THREAD

**Issue by Hubbotu** [anhility/BestInSlotRedux#23]
![wowscrnshot_112817_092518](https://user-images.githubusercontent.com/34053496/33305383-f467ef28-d41e-11e7-95ac-c5e35f4f4b10.jpg)
Hi. Russian localization gives an error. 
https://imgur.com/a/UCqrv

**Comment by Meivyn** [comment]
The `ruRU.lua` file isn't properly written. See: https://github.com/anhility/BestInSlotRedux/pull/24
You can replace your file with this one until a fix is deployed.

**Comment by anhility** [comment]
That is really weird that it don't encode some of the strings. Will look into it.

**Comment by anhility** [comment]
Found the error. On the CurseForge translations page so had each strings a newline at the bottom so the end so the addon encoded the characters wrongly. Fixed them and I'll push a new release later today.
