### ISSUE TITLE
Again the error of Russian localization

### ISSUE THREAD

**Issue by Hubbotu** [anhility/BestInSlotRedux#28]
Everything is missing. Just nothing. =)

https://imgur.com/a/Vhsdd

**Comment by anhility** [comment]
Wut? As in everything is in English instead?

**Comment by Hubbotu** [comment]
https://imgur.com/a/Vhsdd

**Comment by anhility** [comment]
Can you give me a bug report please? You can use Swatter or BugSack to capture it.

Side note: Oh man, I had exactly that UI several years ago. Such memories :)

**Comment by Hubbotu** [comment]
> 1x BestInSlotRedux\Frames\FramesCore.lua:444: invalid option in `format'
[C]: in function `format'
BestInSlotRedux\Frames\FramesCore.lua:444: in function <BestInSlotRedux\Frames\FramesCore.lua:433>
BestInSlotRedux\Frames\FramesCore.lua:899: in function `ShowFrame'
BestInSlotRedux\Frames\FramesCore.lua:906: in function `ToggleFrame'
BestInSlotRedux\MiniMapLDB.lua:15: in function `OnClick'
...dOns\Bartender4\libs\LibDBIcon-1.0\LibDBIcon-1.0-34.lua:116: in function <...dOns\Bartender4\libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:116>

Locals:
(*temporary) = "Создано %. В настоящее время разрабатывается %s."
(*temporary) = "|cffa330c9Beleria|r @ |cff4954e8Argent Dawn-EU|r"
(*temporary) = "|cfff58cbaAnhility|r @ |cff4954e8Ravencrest-EU|r"

**Comment by Hubbotu** [comment]
2x BugSack\sack.lua:376: attempt to index local 'eo' (a nil value)
BugSack\sack.lua:376: in function <BugSack\sack.lua:374>

Locals:
eo = nil
(*temporary) = <function> defined @FrameXML\StaticPopup.lua:3856
(*temporary) = "BugSackSendBugs"
(*temporary) = nil
(*temporary) = "attempt to index local 'eo' (a nil value)"
currentSackContents = <table> {
 1 = <table> {
 }
}
currentErrorIndex = 0
window = BugSackFrame {
 0 = <userdata>
}

**Comment by anhility** [comment]
`(*temporary) = "Создано %. В настоящее время разрабатывается %s."` is missing an s after the first %.
It's a string needed to render the base frame so it crashes the whole addon. I'll fix it immediately and push a new release.
You can add it yourself in the `locale\ruRU.lua` file if you need the addon to work right now.

**Comment by Hubbotu** [comment]
You can throw off the finished file ruRU.lua here?

**Comment by anhility** [comment]
If you open the file, use notepad++ or something so you can see the line number.
Go to line 32 and after the `L["Created by %s. Currently developed by %s."] =` starts the encoded Russian characters. At the end of the first "sentence" should be a lonely `%`. Edit it to `%s`, save the file and start WoW again.

**Comment by Hubbotu** [comment]
working. Thank you

**Comment by anhility** [comment]
Gonna push a new release now. Should be up on Curse soon.
