### ISSUE TITLE
custom item -> too high minimum item level

### ISSUE THREAD

**Issue by Erimioa** [anhility/BestInSlotRedux#45]
if I want to integrade a custom item with BfA, I get the error: "The minimum item level of custom items is 550!" 
With BfA it is a much too high border for custom items. It should be more like 200.

In:"CustomItems.lua", if you change the lines:
11: local minimumIlvl = 550
to 
11: local minimumIlvl = 200

and 
138:   if iLevel < 500 then
to 
138:   if iLevel < 200 then

it works at me.

(funny the old text said 550 and the code checks 500 :)

**Comment by zoveus** [comment]
Hey, thank you for your message.
I fixed this in the developer branch.
Just testing some other things and then there will be an update :)
