### ISSUE TITLE
Custom Items itemlevel requirements outdated

### ISSUE THREAD

**Issue by Pandha** [anhility/BestInSlotRedux#47]
Dear BestInSlotRedux Team,

first of all, thank you for your update. I found one bug, while I want to add a new custom item, which is a Uldir trash drop. The itemlevel to add an Item has to be above 550, which doesn't cover the itemlevel squish.
Have a look to this screenshot: https://i.imgur.com/ZUtgDKj.png

Thank you!

Kind regards,
Pandha

**Comment by zoveus** [comment]
Hey, thank you for your message. This is fixed in addon version 8.0.2.
cheers
Saríth @Tarren Mill
