### ISSUE TITLE
Guild BiS list, sorting by name/class/rank throws an error

### ISSUE THREAD

**Issue by anhility** [anhility/BestInSlotRedux#6]
Might be due to development version. Will test on release version.

**Comment by anhility** [comment]
Gives same error on release version. Might be because the guild BiS DB is empty.
Will test with guild mate imported in DB and see what happens.

**Comment by Meivyn** [comment]
Same as the other. Can't reproduce it since filters are working fine for me.

**Comment by anhility** [comment]
Might be an error on my end. Will test with clean DB.

**Comment by anhility** [comment]
No longer gives me an error. Will reopen if someone else gets the same bug
