### ISSUE TITLE
This addon requires atleast 1 expansion module! Please enable one!

### ISSUE THREAD

**Issue by mahh1998** [anhility/BestInSlotRedux#8]
Says that when i type /bis ingame

**Comment by anhility** [comment]
They should be enabled by default. I'll look into it.

**Comment by anhility** [comment]
Did you enable the modules in the addon list before entering the game? Because that's the only way I can replicate your bug.

**Comment by anhility** [comment]
Error found. A library was miss linked as it had changed its internal file structure.
