### ISSUE TITLE
Report to chat isn't giving clickable links

### ISSUE THREAD

**Issue by anhility** [anhility/BestInSlotRedux#9]
see title

**Comment by Meivyn** [comment]
Did you find why the items aren't clickable yet?

**Comment by anhility** [comment]
Not yet, will work on this after some other stuff are fixed or added.

**Comment by Nitrodroki** [comment]
I believe they never were clickable in the original version, the Raidtieroverview.lua just fetches the list of names in the slots, not the item IDs. Should be feasible tho.

**Comment by anhility** [comment]
Think I saw clickable links in an old screenshot. Will implement it in the future otherwise.
